export const generateComments = () => {
    return [
        '/* eslint-disable */',
        '/* tslint:disable */',
        '/**',
        ' * This is an autogenerated file created by the output-event-listeners-types output.',
        ' * It contains additional typing information for all components that exist in this',
        ' * project and their event listener types.',
        ' */',
        '',
    ].join('\n');
}
